### PR TITLE
chore(): updating nestjs peer dependencies to 9.0.0

### PR DESCRIPTION
**Pull request by quinnjr**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x] Other... Please describe: Chore updating NestJS dependencies.

## What is the current behavior?

NestJS dependencies do not allow for use with 9.x.x branches.

Issue Number: N/A

## What is the new behavior?
Dependencies now allow use with 9.x.x branches.

## Does this PR introduce a breaking change?
- [ ] Yes
- [ x] No

### CODE REVIEW

**Comment by quinnjr** [comment]
@kamilmysliwiec Module could use some TLC

**Comment by DaSchTour** [comment]
Till this is merged and release I published a workaround package. You can drop it into the current installation without changing imports by adding `"@nestjs/ng-universal": "npm:@nestjs-fixed/ng-universal@6.1.2",` to your `package.json`.

**Comment by quinnjr** [comment]
@kamilmysliwiec still in need of a merge

**Comment by quinnjr** [comment]
@DaSchTour can you add ticket creation to your fork?

**Comment by DaSchTour** [comment]
@quinnjr you mean the issues tab? That's done

**Comment by kamilmysliwiec** [comment]
Fixed in this PR https://github.com/nestjs/ng-universal/pull/943

**Pull request closed without merging**
