### PR TITLE
feat: add errorHandler as an option in case of rendering error

### PR DESCRIPTION
**Pull request by bpopnikolov**
## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently if there is an error during the server rendering the server fails silently without the possibility to hook-up in the rendering process and handle the error (ex: return an error page or the default index.html without SSR for browser fallback).

Issue Number: N/A

## What is the new behavior?
Added an option to be able to pass an error handler for custom error handling logic. By default the error logged in the console and the renderingCallback is resolved with the error in order to make debugging easier. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by bpopnikolov** [comment]
@kamilmysliwiec could you give a look at this PR please? Do you think that this feature request can be merged?

**Comment by etienne-bc** [comment]
I'd love to have something like this ❤️

**Comment by jsaguet** [comment]
This is a must-have feature in my company that we are currently lacking. 
@kamilmysliwiec Do you think we could expect this to be merged soon ? It would be awesome

**Comment by bpop-bc** [comment]
I'm not sure if this is the right solution to the problem I'm trying to address but I'd be more than happy to implement a different approach if there are any recommendations.

**Comment by bpopnikolov** [comment]
I'm not sure if this is the right solution to the problem that I'm trying to address with this PR but I'd be more than happy to implement something else if there are any recommendations.

**Comment by feihan** [comment]
that feature would be absolutely needed.

**Comment by kamilmysliwiec** [comment]
Thank you! Added in 4.1.0

**Pull request merged**
