### PR TITLE
fix: export REQUEST, RESPONSE tokens

### PR DESCRIPTION
**Pull request by AliYusuf95**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #573

## What is the new behavior?
Tokens can be imported directly from `@nestjs/ng-universal`

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Review by micalevisk — COMMENTED** [review]
since the README saids we must import them from `@nestjs/ng-universal/tokens`:

image

you shouldn't add that export to `lib/index.ts`. Your commit actually reverts 508bba7eddd6a638d342e6bc587c8587c9bb226a but I guess something was missed in that one because currently `npm run build` will leave us with the following structure:

```
.
├── CONTRIBUTING.md
├── dist
│   ├── angular-universal.constants.d.ts
│   ├── angular-universal.constants.js
│   ├── angular-universal.module.d.ts
│   ├── angular-universal.module.js
│   ├── angular-universal.providers.d.ts
│   ├── angular-universal.providers.js
│   ├── cache
│   ├── index.d.ts
│   ├── index.js
│   ├── interfaces
│   ├── lib
│   ├── tokens.d.ts
│   ├── tokens.js
│   └── utils
├── index.d.ts
├── index.js
├── index.ts
├── jest.config.js
├── lib
│   ├── angular-universal.constants.ts
│   ├── angular-universal.module.ts
│   ├── angular-universal.providers.ts
│   ├── cache
│   ├── index.ts
│   ├── interfaces
│   ├── tokens.ts
│   └── utils
├── LICENSE
├── package.json
├── package-lock.json
├── README.md
├── renovate.json
├── schematics
│   ├── collection.json
│   └── install
├── tsconfig.json
├── tsconfig.schematics.json
└── tslint.json
```

so there's no `tokens.d.ts` nor `tokens/index.d.ts` (at the root) to resolve to

**Comment by AliYusuf95** [comment]
@micalevisk thank you, I didn't notice that.
I created new `tokens.ts` on the root to solve the issue. Also, I reverted changes in `lib/index.ts`

**Comment by AliYusuf95** [comment]
@kamilmysliwiec Since the current `index.ts` in the root it's not affected by the `build` command due to the wrong path in `tsconfig.json`. I suggest having a separate command to build the root `index` and `tokens`.

**Comment by bastienlemaitre** [comment]
Up

**Comment by DaSchTour** [comment]
😩

**Comment by DaSchTour** [comment]
@kamilmysliwiec would you please consider merging this PR before releasing a new version?

**Comment by DaSchTour** [comment]
As a workaround I just published a package with this fix. You can drop it into the current installation without changing imports by adding `"@nestjs/ng-universal": "npm:@nestjs-fixed/ng-universal@6.1.2",` to your `package.json`.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/ng-universal/pull/688#pullrequestreview-835732884

**Pull request closed without merging**
